
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AdminHomeComponent': typeof import("../components/admin/HomeComponent.vue")['default']
    'AdminUsersComponent': typeof import("../components/admin/UsersComponent.vue")['default']
    'AuthLoginComponent': typeof import("../components/auth/LoginComponent.vue")['default']
    'AuthRegisterComponent': typeof import("../components/auth/RegisterComponent.vue")['default']
    'FooterComponent': typeof import("../components/footer/FooterComponent.vue")['default']
    'HeaderComponent': typeof import("../components/header/HeaderComponent.vue")['default']
    'NavigationNDAdmin': typeof import("../components/navigation/NDAdmin.vue")['default']
    'NavigationNDIndex': typeof import("../components/navigation/NDIndex.vue")['default']
    'NavigationNDTeacher': typeof import("../components/navigation/NDTeacher.vue")['default']
    'PythonRealTimeFaceDetection': typeof import("../components/python/RealTimeFaceDetection.vue")['default']
    'PythonCheckDayComponent': typeof import("../components/python/check/DayComponent.vue")['default']
    'PythonCheckFaceDetection': typeof import("../components/python/check/FaceDetection.vue")['default']
    'SettingsProfileComponent': typeof import("../components/settings/ProfileComponent.vue")['default']
    'TeacherHomeComponent': typeof import("../components/teacher/HomeComponent.vue")['default']
    'TeacherImageCheckComponent': typeof import("../components/teacher/ImageCheckComponent.vue")['default']
    'TeacherImageViewComponent': typeof import("../components/teacher/ImageViewComponent.vue")['default']
    'TeacherInputDataComponent': typeof import("../components/teacher/InputDataComponent.vue")['default']
    'TeacherStudentComponent': typeof import("../components/teacher/StudentComponent.vue")['default']
    'TeacherCheckDayComponent': typeof import("../components/teacher/check/DayComponent.vue")['default']
    'TeacherCheckStepperComponent': typeof import("../components/teacher/check/StepperComponent.vue")['default']
    'TeacherViewAllStudentViewCompomponent': typeof import("../components/teacher/view-all/studentViewCompomponent.vue")['default']
    'TeacherViewCheckIineComponent': typeof import("../components/teacher/view/CheckIineComponent.vue")['default']
    'TeacherViewDayComponent': typeof import("../components/teacher/view/DayComponent.vue")['default']
    'UsersIndexComponent': typeof import("../components/users/IndexComponent.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAdminHomeComponent': typeof import("../components/admin/HomeComponent.vue")['default']
    'LazyAdminUsersComponent': typeof import("../components/admin/UsersComponent.vue")['default']
    'LazyAuthLoginComponent': typeof import("../components/auth/LoginComponent.vue")['default']
    'LazyAuthRegisterComponent': typeof import("../components/auth/RegisterComponent.vue")['default']
    'LazyFooterComponent': typeof import("../components/footer/FooterComponent.vue")['default']
    'LazyHeaderComponent': typeof import("../components/header/HeaderComponent.vue")['default']
    'LazyNavigationNDAdmin': typeof import("../components/navigation/NDAdmin.vue")['default']
    'LazyNavigationNDIndex': typeof import("../components/navigation/NDIndex.vue")['default']
    'LazyNavigationNDTeacher': typeof import("../components/navigation/NDTeacher.vue")['default']
    'LazyPythonRealTimeFaceDetection': typeof import("../components/python/RealTimeFaceDetection.vue")['default']
    'LazyPythonCheckDayComponent': typeof import("../components/python/check/DayComponent.vue")['default']
    'LazyPythonCheckFaceDetection': typeof import("../components/python/check/FaceDetection.vue")['default']
    'LazySettingsProfileComponent': typeof import("../components/settings/ProfileComponent.vue")['default']
    'LazyTeacherHomeComponent': typeof import("../components/teacher/HomeComponent.vue")['default']
    'LazyTeacherImageCheckComponent': typeof import("../components/teacher/ImageCheckComponent.vue")['default']
    'LazyTeacherImageViewComponent': typeof import("../components/teacher/ImageViewComponent.vue")['default']
    'LazyTeacherInputDataComponent': typeof import("../components/teacher/InputDataComponent.vue")['default']
    'LazyTeacherStudentComponent': typeof import("../components/teacher/StudentComponent.vue")['default']
    'LazyTeacherCheckDayComponent': typeof import("../components/teacher/check/DayComponent.vue")['default']
    'LazyTeacherCheckStepperComponent': typeof import("../components/teacher/check/StepperComponent.vue")['default']
    'LazyTeacherViewAllStudentViewCompomponent': typeof import("../components/teacher/view-all/studentViewCompomponent.vue")['default']
    'LazyTeacherViewCheckIineComponent': typeof import("../components/teacher/view/CheckIineComponent.vue")['default']
    'LazyTeacherViewDayComponent': typeof import("../components/teacher/view/DayComponent.vue")['default']
    'LazyUsersIndexComponent': typeof import("../components/users/IndexComponent.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AdminHomeComponent: typeof import("../components/admin/HomeComponent.vue")['default']
export const AdminUsersComponent: typeof import("../components/admin/UsersComponent.vue")['default']
export const AuthLoginComponent: typeof import("../components/auth/LoginComponent.vue")['default']
export const AuthRegisterComponent: typeof import("../components/auth/RegisterComponent.vue")['default']
export const FooterComponent: typeof import("../components/footer/FooterComponent.vue")['default']
export const HeaderComponent: typeof import("../components/header/HeaderComponent.vue")['default']
export const NavigationNDAdmin: typeof import("../components/navigation/NDAdmin.vue")['default']
export const NavigationNDIndex: typeof import("../components/navigation/NDIndex.vue")['default']
export const NavigationNDTeacher: typeof import("../components/navigation/NDTeacher.vue")['default']
export const PythonRealTimeFaceDetection: typeof import("../components/python/RealTimeFaceDetection.vue")['default']
export const PythonCheckDayComponent: typeof import("../components/python/check/DayComponent.vue")['default']
export const PythonCheckFaceDetection: typeof import("../components/python/check/FaceDetection.vue")['default']
export const SettingsProfileComponent: typeof import("../components/settings/ProfileComponent.vue")['default']
export const TeacherHomeComponent: typeof import("../components/teacher/HomeComponent.vue")['default']
export const TeacherImageCheckComponent: typeof import("../components/teacher/ImageCheckComponent.vue")['default']
export const TeacherImageViewComponent: typeof import("../components/teacher/ImageViewComponent.vue")['default']
export const TeacherInputDataComponent: typeof import("../components/teacher/InputDataComponent.vue")['default']
export const TeacherStudentComponent: typeof import("../components/teacher/StudentComponent.vue")['default']
export const TeacherCheckDayComponent: typeof import("../components/teacher/check/DayComponent.vue")['default']
export const TeacherCheckStepperComponent: typeof import("../components/teacher/check/StepperComponent.vue")['default']
export const TeacherViewAllStudentViewCompomponent: typeof import("../components/teacher/view-all/studentViewCompomponent.vue")['default']
export const TeacherViewCheckIineComponent: typeof import("../components/teacher/view/CheckIineComponent.vue")['default']
export const TeacherViewDayComponent: typeof import("../components/teacher/view/DayComponent.vue")['default']
export const UsersIndexComponent: typeof import("../components/users/IndexComponent.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAdminHomeComponent: typeof import("../components/admin/HomeComponent.vue")['default']
export const LazyAdminUsersComponent: typeof import("../components/admin/UsersComponent.vue")['default']
export const LazyAuthLoginComponent: typeof import("../components/auth/LoginComponent.vue")['default']
export const LazyAuthRegisterComponent: typeof import("../components/auth/RegisterComponent.vue")['default']
export const LazyFooterComponent: typeof import("../components/footer/FooterComponent.vue")['default']
export const LazyHeaderComponent: typeof import("../components/header/HeaderComponent.vue")['default']
export const LazyNavigationNDAdmin: typeof import("../components/navigation/NDAdmin.vue")['default']
export const LazyNavigationNDIndex: typeof import("../components/navigation/NDIndex.vue")['default']
export const LazyNavigationNDTeacher: typeof import("../components/navigation/NDTeacher.vue")['default']
export const LazyPythonRealTimeFaceDetection: typeof import("../components/python/RealTimeFaceDetection.vue")['default']
export const LazyPythonCheckDayComponent: typeof import("../components/python/check/DayComponent.vue")['default']
export const LazyPythonCheckFaceDetection: typeof import("../components/python/check/FaceDetection.vue")['default']
export const LazySettingsProfileComponent: typeof import("../components/settings/ProfileComponent.vue")['default']
export const LazyTeacherHomeComponent: typeof import("../components/teacher/HomeComponent.vue")['default']
export const LazyTeacherImageCheckComponent: typeof import("../components/teacher/ImageCheckComponent.vue")['default']
export const LazyTeacherImageViewComponent: typeof import("../components/teacher/ImageViewComponent.vue")['default']
export const LazyTeacherInputDataComponent: typeof import("../components/teacher/InputDataComponent.vue")['default']
export const LazyTeacherStudentComponent: typeof import("../components/teacher/StudentComponent.vue")['default']
export const LazyTeacherCheckDayComponent: typeof import("../components/teacher/check/DayComponent.vue")['default']
export const LazyTeacherCheckStepperComponent: typeof import("../components/teacher/check/StepperComponent.vue")['default']
export const LazyTeacherViewAllStudentViewCompomponent: typeof import("../components/teacher/view-all/studentViewCompomponent.vue")['default']
export const LazyTeacherViewCheckIineComponent: typeof import("../components/teacher/view/CheckIineComponent.vue")['default']
export const LazyTeacherViewDayComponent: typeof import("../components/teacher/view/DayComponent.vue")['default']
export const LazyUsersIndexComponent: typeof import("../components/users/IndexComponent.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
